git:
  paging:
    colorArg: always
gui:
  border: hidden
  enlargedSideViewLocation: top
  mainPanelSplitMode: horizontal
  nerdFontsVersion: "3"
  screenMode: half
  sidePanelWidth: 0.15
  showCommandLog: false
  showListFooter: false
  showNumstatInFilesView: true
  showRandomTip: false
keybinding:
  commits:
    copyCommitAttributeToClipboard: "<c-o>"
  files:
    copyFileInfoToClipboard: "<c-o>"
  universal:
    copyToClipboard: "y"
    prevPage: <disabled>
    nextPage: <disabled>
    prevBlock: ","
    nextBlock: "."
os:
  editPreset: nvim
promptToReturnFromSubprocess: false
update:
  method: never
