git:
  paging:
    colorArg: always
gui:
  border: single
  mainPanelSplitMode: horizontal
  nerdFontsVersion: "3"
  sidePanelWidth: 0.25
  showCommandLog: false
  showListFooter: false
  showNumstatInFilesView: true
  showRandomTip: false
keybinding:
  commits:
    copyCommitAttributeToClipboard: "<c-o>"
  files:
    copyFileInfoToClipboard: "<c-o>"
  universal:
    copyToClipboard: y
    prevItem: k
    nextItem: j
    prevPage: <disabled>
    nextPage: <disabled>
    prevBlock: K
    nextBlock: J
    scrollUpMain: <up>
    scrollDownMain: <down>
os:
  editPreset: nvim
promptToReturnFromSubprocess: false
update:
  method: never
