- hosts: localhost
  connection: local

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    blesh_dir: "{{ home }}/.local/share/blesh"

  tasks:
    - name: blesh
      block:
        - name: blesh download
          get_url:
            url: https://github.com/akinomyoga/ble.sh/releases/download/nightly/ble-nightly.tar.xz
            dest: /tmp/ble-nightly.tar.xz

        - name: blesh extract
          unarchive:
            src: /tmp/ble-nightly.tar.xz
            dest: /tmp

        - name: blesh install
          shell: "bash /tmp/ble-nightly/ble.sh --install ~/.local/share"
      when: blesh_dir is not directory

    - name: elixir-ls
      ansible.builtin.file:
        src: "{{ home }}/.local/share/nvim/mason/packages/elixir-ls/language_server.sh"
        dest: "{{ home }}/.local/bin/elixir-ls"
        state: link

# vim:ft=yaml.ansible
