- name: blesh prepare
  ansible.builtin.unarchive:
    src: https://github.com/akinomyoga/ble.sh/releases/download/nightly/ble-nightly.tar.xz
    dest: /tmp
    remote_src: true
  tags:
    - blesh

- name: blesh install
  ansible.builtin.command:
    cmd: "bash /tmp/ble-nightly/ble.sh --install {{ home }}/.local/share"
    creates: "{{ home }}/.local/share/blesh"
  tags:
    - blesh

# vim: ft=yaml.ansible

