http:
  routers:
    app-router:
      rule: "Host(`localhost`)"
      entryPoints:
        - web
      service: app-service

  services:
    app-service:
      loadBalancer:
        servers:
          - url: "http://localhost:4000"

