- hosts: localhost

  vars:
    home: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: .local
      ansible.builtin.file:
        path: "{{ home }}/{{ item }}"
        mode: "0755"
        state: directory
      loop:
        - .local
        - .local/share
        - .local/share/backgrounds
        - .local/share/fonts
      tags:
        - backgrounds
        - fonts

    - name: "link asset files"
      ansible.builtin.file:
        src: "{{ item.src }}"
        path: "{{ home }}/.local/share/backgrounds/{{ item.path }}"
        state: link
      with_community.general.filetree:
        - files/backgrounds/
      when: item.state == 'file'
      tags:
        - backgrounds

    - name: download nerd fonts
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/NerdFontsSymbolsOnly.zip
        dest: /tmp
        remote_src: true
      tags:
        - fonts

    - name: install nerd fonts
      ansible.builtin.file:
        path: "{{ home }}/.local/share/fonts/{{ item | basename }}"
        state: file
      with_fileglob:
        - /tmp/SymbolsNerdFont*.ttf
      tags:
        - fonts


# vim: ft=yaml.ansible
