- name: host
  hosts: localhost
  connection: local
  vars:
    home: "{{ lookup('env', 'HOME') }}"
  roles:
    - distrobox

- name: box
  hosts: boxes
  roles:
    - node
    - box

# vim: ft=yaml.ansible
