- name: host
  hosts: localhost
  connection: local
  roles:
    - distrobox

- name: box
  hosts: boxes
  roles:
    - box
    - common

- name: dot
  hosts: dot
  connection: community.podman.podman

  tasks:
    - name: packages
      community.general.pacman:
        name:
          - ansible-language-server
          - ansible-lint
          - lua-language-server
          - stylua
          - yaml-language-server
        state: present
      tags: packages

# vim: ft=yaml.ansible
