- name: host
  hosts: localhost
  connection: local
  vars:
    home: "{{ lookup('env', 'HOME') }}"
  roles:
    - distrobox

- name: chj
  hosts: chj
  roles:
    - postgres

- name: box
  hosts: boxes
  roles:
    - node
    - box

- name: chr
  hosts: chr
  roles:
    - postgres
    - elixir

- name: agt
  hosts: agt
  roles:
    - elixir

# vim: ft=yaml.ansible
