- hosts: localhost

  tasks:
    - name: dev tools
      community.general.homebrew:
        name:
          - bat
          - eza
          - fd
          - fzf
          - gh
          - jq
          - lazygit
          - ripgrep
          - starship
        update_homebrew: true
        upgrade_all: true
