- name: ".config [global]"
  ansible.builtin.import_playbook: shared/config.yml
  tags:
    - config

- name: "other files [global]"
  vars:
    files_local:
      - "files"
  ansible.builtin.import_playbook: shared/files.yml

- name: "other files [container]"
  vars:
    files_local:
      - "files"
  ansible.builtin.import_playbook: container/files.yml

- name: "Container-specific configuration [root]"
  ansible.builtin.import_playbook: container/root.yml

- name: "Container-specific configuration [user]"
  ansible.builtin.import_playbook: container/user.yml

# vim:ft=yaml.ansible
