- hosts: localhost
  connection: local
  become: true
  become_method: sudo

  tasks:
    - name: locale
      community.general.locale_gen:
        name: en_US.UTF-8
        state: present

    - name: chaotic-aur
      block:
        - name: pacman key
          community.general.pacman_key:
            id: ef925ea60f33d0cb85c44ad13056513887b78aeb
            keyserver: keyserver.ubuntu.com
            state: present

        - name: repo packages
          community.general.pacman:
            name:
              - https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst
              - https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst

        - name: pacman config
          community.general.ini_file:
            path: /etc/pacman.conf
            section: chaotic-aur
            option: Include
            value: /etc/pacman.d/chaotic-mirrorlist
            state: present

    - name: packages
      community.general.pacman:
        name:
          - atuin
          - bat
          - direnv
          - eza
          - fd
          - github-cli
          - git-delta
          - kitty
          - lazydocker
          - lazygit
          - neovim
          - nodejs
          - npm
          - ripgrep
          - ruby
          - starship
          - wl-clipboard
          - yay
        update_cache: true

    - name: direnv host exec
      ansible.builtin.copy:
        dest: /usr/bin/direnv-host-exec
        content: |
          #!/bin/sh
          exec distrobox-host-exec direnv exec . "$@"
        mode: 0755

# vim:ft=yaml.ansible
