- hosts: localhost
  connection: local
  become: true
  become_method: sudo

  tasks:
    - name: locale
      community.general.locale_gen:
        name: en_US.UTF-8
        state: present

    - name: chaotic-aur
      block:
        - name: pacman key
          community.general.pacman_key:
            id: ef925ea60f33d0cb85c44ad13056513887b78aeb
            keyserver: keyserver.ubuntu.com
            state: present

        - name: repo packages
          community.general.pacman:
            name:
              - https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst
              - https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst

        - name: pacman config
          community.general.ini_file:
            path: /etc/pacman.conf
            mode: "0644"
            section: chaotic-aur
            option: Include
            value: /etc/pacman.d/chaotic-mirrorlist
            state: present

    - name: packages
      community.general.pacman:
        name:
          - atuin
          - bat
          - direnv
          - eza
          - fd
          - fzf
          - github-cli
          - jq
          - kitty
          - lazydocker
          - lazygit
          - neovim
          - nodejs
          - npm
          - org.freedesktop.secrets
          - ripgrep
          - ruby
          - starship
          - wl-clipboard
          - yay
        update_cache: true

    - name: packages
      community.general.pacman:
        name:
          - python-jsondiff
      when: "lookup('env', 'CONTAINER_ID') == 'chr'"

    - name: direnv host exec
      ansible.builtin.copy:
        dest: /usr/local/bin/docker
        content: |
          #!/bin/bash
          exec distrobox-host-exec direnv exec . docker "$@"
        mode: "0755"

    - name: scripts
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "/usr/local/bin/{{ item.path }}"
        state: link
      with_community.general.filetree: "scripts/"

- name: blesh
  import_playbook: packages/blesh.yaml

# vim: ft=yaml.ansible
