- name: container
  import_playbook: container.yaml

- name: emp customizations
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: packages
      community.general.pacman:
        name:
          - nodejs
          - npm
        state: present

# vim: ft=yaml.ansible
