- name: "files"
  hosts: localhost
  connection: local

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    files_local: "files/"

  tasks:
    - name: "create subdirs"
      ansible.builtin.file:
        path: "{{ home }}/{{ item.path | regex_replace('^_', '.') }}"
        mode: "0700"
        state: directory
      with_community.general.filetree: "{{ files_local }}"
      when: item.state == 'directory'

    - name: "link application shortcuts"
      ansible.builtin.file:
        src: "{{ item.src }}"
        path: "{{ home }}/.local/share/applications/{{ item.path }}"
        state: link
      with_community.general.filetree: "{{ files_local }}_local/share/applications"
      when: item.state == 'file'
      tags: apps

    - name: "link files"
      ansible.builtin.file:
        src: "{{ item.src }}"
        path: "{{ home }}/{{ item.path | regex_replace('^_', '.') }}"
        state: link
      with_community.general.filetree: "{{ files_local }}"
      when: item.state == 'file'

# vim: ft=yaml.ansible
