- hosts: localhost

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    application_home: "{{ home }}/.local/share/applications"
    worktree_home: "{{ home }}/Worktrees"

  tasks:
    - name: .local
      ansible.builtin.file:
        path: "{{ home }}/{{ item }}"
        mode: "0755"
        state: directory
      loop:
        - "{{ home }}/.config"
        - "{{ home }}/.local/bin"
        - "{{ home }}/.local/share/applications"
        - "{{ home }}/.local/share/backgrounds"
        - "{{ home }}/.local/share/fonts"
      when: "(home + '/' + item) is not directory"
      tags:
        - assets
        - backgrounds
        - config
        - fonts
        - local

    - name: "link asset files"
      ansible.builtin.file:
        src: "{{ item.src }}"
        path: "{{ home }}/.local/share/backgrounds/{{ item.path }}"
        state: link
      with_community.general.filetree:
        - files/backgrounds/
      when: item.state == 'file'
      tags:
        - assets
        - backgrounds

    - name: download nerd fonts
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/NerdFontsSymbolsOnly.zip
        dest: /tmp
        remote_src: true
      tags:
        - assets
        - fonts

    - name: install nerd fonts
      ansible.builtin.file:
        path: "{{ home }}/.local/share/fonts/{{ item | basename }}"
        state: file
      with_fileglob:
        - /tmp/SymbolsNerdFont*.ttf
      tags:
        - assets
        - fonts

    - name: "create config subdirs"
      ansible.builtin.file:
        path: "{{ home }}/.config/{{ item.path }}"
        mode: "0755"
        state: directory
      with_community.general.filetree:
        - files/config/
        - secrets/config/
      when: "item.state == 'directory' and (home + '/.config/' + item.path) is not directory"
      tags:
        - config

    - name: "link config files"
      ansible.builtin.file:
        src: "{{ item.src }}"
        path: "{{ home }}/.config/{{ item.path }}"
        state: link
      with_community.general.filetree:
        - files/config/
        - secrets/config/
      when: "item.state == 'file' and (home + '/.config/' + item.path) is not link"
      tags:
        - config
        - worktrees

    - name: "remove default files"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ home }}/.bashrc"
        - "{{ home }}/.bash_profile"
        - "{{ home }}/.profile"
      when: item is not link
      tags:
        - config

    - name: "link home root files"
      ansible.builtin.file:
        src: "{{ item.src }}"
        path: "{{ home }}/.{{ item.path }}"
        state: link
      with_community.general.filetree:
        - files/home/
      when: item.path is not link
      tags:
        - config

    - name: "link .local files"
      ansible.builtin.file:
        src: "{{ item.src }}"
        path: "{{ home }}/.local/{{ item.path }}"
        state: link
      with_community.general.filetree:
        - files/local/
      when: item.state == 'file'
      tags:
        - local

    - name: initialize worktree list
      ansible.builtin.set_fact:
        worktrees: []
      tags:
        - worktrees

# vim: ft=yaml.ansible
