# TODO:
# For some reason, I am unable to use dconf to reset some keys I use regularly
# (<Super>period, <Control><Shift>u). Until I figure a way to do it automatically
# the solution is to run ibus-setup and delete the keybindings manually.
#
# `ibus-setup` must be run using the system python interpreter. This is done by
# running ibus-setup with a custom path, like so:
#
#     PATH=/usr/bin:$PATH ibus-setup
#
- hosts: localhost
  connection: local

  vars:
    extensions:
      - file: azwallpaperazwallpaper.gitlab.com.v11.shell-extension.zip
        name: azwallpaper@azwallpaper.gitlab.com
      - file: dash-to-paneljderose9.github.com.v68.shell-extension.zip
        name: dash-to-panel@jderose9.github.com
      - file: paperwmpaperwm.github.com.v138.shell-extension.zip
        name: paperwm@paperwm.github.com
      - file: just-perfection-desktopjust-perfection.v34.shell-extension.zip
        name: just-perfection-desktop@just-perfection

    settings:
      - key: "/system/locale/region"
        value: "'pt_PT.UTF-8'"

      - key: "/org/freedesktop/ibus/panel/emoji/hotkey"
        value: "['']"

      - key: "/org/gnome/desktop/input-sources/per-window"
        value: "true"

      - key: "/org/gnome/desktop/wm/keybindings/switch-input-source"
        value: "['<Shift><Control><Alt>apostrophe']"

      - key: "/org/gnome/desktop/interface/accent-color"
        value: "'yellow'"
      - key: "/org/gnome/desktop/interface/clock-format"
        value: "'24h'"
      - key: "/org/gnome/desktop/interface/color-scheme"
        value: "'prefer-dark'"
      - key: "/org/gnome/desktop/interface/document-font-name"
        value: "'Inter 11'"
      - key: "/org/gnome/desktop/interface/font-antialiasing"
        value: "'grayscale'"
      - key: "/org/gnome/desktop/interface/font-name"
        value: "'Inter 11'"
      - key: "/org/gnome/desktop/interface/monospace-font-name"
        value: "'JetBrains Mono 11'"

      - key: "/org/gnome/desktop/wm/keybindings/close"
        value: "['<Shift><Control><Alt>q']"
      - key: "/org/gnome/desktop/wm/keybindings/minimize"
        value: "['']"

      - key: "/org/gnome/desktop/wm/preferences/workspace-names"
        value: "['sys', 'chr']"

      - key: "/org/gnome/mutter/overlay-key"
        value: "''"

      - key: "/org/gnome/settings-daemon/plugins/media-keys/screensaver"
        value: "['']"
      - key: "/org/gnome/settings-daemon/plugins/media-keys/home"
        value: "['']"

      - key: "/org/gnome/shell/extensions/azwallpaper/slideshow-slide-duration"
        value: "(0, 5, 0)"
      - key: "/org/gnome/shell/extensions/azwallpaper/slideshow-directory"
        value: "'/var/home/david/.local/share/backgrounds'"

      - key: "/org/gnome/shell/extensions/blur-my-shell/applications/blur"
        value: "true"
      - key: "/org/gnome/shell/extensions/blur-my-shell/applications/whitelist"
        value: "['kitty']"

      - key: "/org/gnome/shell/extensions/dash-to-panel/stockgs-keep-dash"
        value: "true"
      - key: "/org/gnome/shell/extensions/dash-to-panel/trans-use-custom-opacity"
        value: "true"

      - key: "/org/gnome/shell/extensions/search-light/scale-height"
        value: "0.0"
      - key: "/org/gnome/shell/extensions/search-light/scale-width"
        value: "0.0"
      - key: "/org/gnome/shell/extensions/search-light/shortcut-search"
        value: "['<Shift><Control><Alt>a']"

      - key: "/org/gnome/shell/extensions/paperwm/cycle-width-steps"
        value: "[0.55, 0.77, 1.0]"
      - key: "/org/gnome/shell/extensions/paperwm/default-focus-mode"
        value: "1"
      - key: "/org/gnome/shell/extensions/paperwm/horizontal-margin"
        value: "6"
      - key: "/org/gnome/shell/extensions/paperwm/selection-border-radius-top"
        value: "0"
      - key: "/org/gnome/shell/extensions/paperwm/selection-border-size"
        value: "0"
      - key: "/org/gnome/shell/extensions/paperwm/show-window-position-bar"
        value: "false"
      - key: "/org/gnome/shell/extensions/paperwm/vertical-margin"
        value: "6"
      - key: "/org/gnome/shell/extensions/paperwm/vertical-margin-bottom"
        value: "6"
      - key: "/org/gnome/shell/extensions/paperwm/window-gap"
        value: "6"
      - key: "/org/gnome/shell/extensions/paperwm/keybindings/cycle-width"
        value: "['<Shift><Control><Alt>u']"
      - key: "/org/gnome/shell/extensions/paperwm/keybindings/cycle-width-backwards"
        value: "['<Shift><Control><Alt>i']"
      - key: "/org/gnome/shell/extensions/paperwm/keybindings/move-down-workspace"
        value: "['<Shift><Control><Alt><Super>j']"
      - key: "/org/gnome/shell/extensions/paperwm/keybindings/move-left"
        value: "['<Shift><Control><Alt><Super>h']"
      - key: "/org/gnome/shell/extensions/paperwm/keybindings/move-right"
        value: "['<Shift><Control><Alt><Super>l']"
      - key: "/org/gnome/shell/extensions/paperwm/keybindings/move-up-workspace"
        value: "['<Shift><Control><Alt><Super>k']"
      - key: "/org/gnome/shell/extensions/paperwm/keybindings/switch-down-workspace"
        value: "['<Shift><Control><Alt>j']"
      - key: "/org/gnome/shell/extensions/paperwm/keybindings/switch-left"
        value: "['<Shift><Control><Alt>h']"
      - key: "/org/gnome/shell/extensions/paperwm/keybindings/switch-next"
        value: "['']"
      - key: "/org/gnome/shell/extensions/paperwm/keybindings/switch-previous"
        value: "['']"
      - key: "/org/gnome/shell/extensions/paperwm/keybindings/switch-right"
        value: "['<Shift><Control><Alt>l']"
      - key: "/org/gnome/shell/extensions/paperwm/keybindings/switch-up-workspace"
        value: "['<Shift><Control><Alt>k']"

        # Favorite app shortcuts
      - key: "/org/gnome/shell/favorite-apps"
        value: "['com.discordapp.Discord.desktop', 'com.rtosta.zapzap.desktop']"
      - key: "/org/gnome/shell/keybindings/switch-to-application-1"
        value: "['<Shift><Control><Alt>d']"
      - key: "/org/gnome/shell/keybindings/switch-to-application-2"
        value: "['<Shift><Control><Alt>z']"

      - key: "/org/gnome/shell/keybindings/toggle-overview"
        value: "['<Shift><Control><Alt>o']"
      - key: "/org/gnome/shell/keybindings/toggle-quick-settings"
        value: "['']"

      - key: "/org/gtk/settings/file-chooser/clock-format"
        value: "'24'"

  tasks:
    - name: enable bluefin gnome extensions
      shell: "gnome-extensions enable {{ item }}"
      loop:
        - caffeine@patapon.info

    - name: disable bluefin gnome extensions
      shell: "gnome-extensions disable {{ item }}"
      loop:
        - apps-menu@gnome-shell-extensions.gcampax.github.com
        - dash-to-dock@micxgx.gmail.com
        - logomenu@aryan_k
        - tailscale@joaophi.github.com

    - name: download gnome extensions
      get_url:
        url: "https://extensions.gnome.org/extension-data/{{ item.file }}"
        dest: "/tmp/{{ item.file }}"
      loop: "{{ extensions }}"

    - name: install gnome extensions
      command: "gnome-extensions install /tmp/{{ item.file }}"
      loop: "{{ extensions }}"
      ignore_errors: true

    - name: enable gnome extensions
      command: "gnome-extensions enable {{ item.name }}"
      loop: "{{ extensions }}"
      ignore_errors: true

    - name: tweak gnome settings
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop: "{{ settings }}"

    - name: tweak gnome settings
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        value: "[('xkb', 'us'), ('xkb', 'us+intl')]"

    - name: tweak gnome settings
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/mru-sources"
        value: "[('xkb', 'us')]"
