- hosts: localhost
  connection: local

  vars:
    base_paths:
      - "base"
      - "boxes/all"
      - "boxes/{{ box_name }}"
      - "secrets"
      - "{{ ('traits/' + trait) if trait is defined }}"

  tasks:
    - name: "create directories"
      ansible.builtin.file:
        path: "{{ home }}/{{ item }}"
        state: directory
        owner: david
        group: david
        mode: "0700"
      loop:
        - ".cache"
        - ".config"
        - ".local/bin"
        - ".local/share"
        - ".local/share/aider"
        - ".local/state/aider/aider.tags.cache.v4"
        - "trunk"

    - name: "create subdirs"
      ansible.builtin.file:
        path: "{{ home }}/{{ item.path | regex_replace('^_', '.') }}"
        state: directory
      with_filetree: "{{ base_paths | reject('==', '') }}"
      when: item.state == 'directory'

    - name: "link files"
      ansible.builtin.file:
        src: "{{ item.src }}"
        path: "{{ home }}/{{ item.path | regex_replace('^_', '.') }}"
        state: link
      with_filetree: "{{ base_paths | reject('==', '') }}"
      when: item.state == 'file'

    - name: "touch aider files"
      ansible.builtin.copy:
        content: ""
        dest: "{{ home }}/.local/state/aider/{{ item }}"
        force: false
      loop:
        - "aider.chat.history.md"
        - "aider.input.history"
      when: box_name is defined
