- name: ".config [global]"
  ansible.builtin.import_playbook: shared/config.yml

- name: "other files [global]"
  vars:
    files_local:
      - "../shared/files"
      - "../host/files"
  ansible.builtin.import_playbook: shared/files.yml

- name: "gnome"
  ansible.builtin.import_playbook: host/gnome.yml
