- hosts: localhost

  vars:
    version: "0.42.2"

    base_url: "https://github.com/kovidgoyal/kitty/releases/download"

    home: "{{ lookup('env', 'HOME') }}"
    bin: "{{ home }}/.local/bin"
    app: "{{ home }}/.local/app"
    kitty: "{{ app }}/kitty/{{ version }}"

  tasks:
    - name: kitty dir
      ansible.builtin.file:
        path: "{{ app }}/kitty/{{ version }}"
        state: directory
        mode: "0755"

    - name: kitty download
      ansible.builtin.get_url:
        url: "{{ base_url }}/v{{ version }}/kitty-{{ version }}-x86_64.txz"
        dest: "/tmp/kitty-{{ version }}-x86_64.txz"
        mode: "0644"

    - name: kitty extract
      ansible.builtin.unarchive:
        src:  "/tmp/kitty-{{ version }}-x86_64.txz"
        dest: "{{ kitty }}"
        creates: "{{ kitty }}/bin/kitty"

    - name: kitty link
      ansible.builtin.file:
        src: "{{ kitty }}/bin/{{ item }}"
        dest: "{{ bin }}/{{ item }}"
        state: link
      loop:
        - kitty
        - kitten

# vim: ft=yaml.ansible
