- hosts: localhost
  connection: local

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    blesh_dir: "{{ home }}/.local/share/blesh"
    kitty_dir: "{{ home }}/.local/kitty.app"

  tasks:
    - name: brew
      community.general.homebrew:
        name:
          - ansible
          - ansible-language-server
          - atuin
          - bat
          - block-goose-cli
          - direnv
          - elixir-ls
          - eza
          - fd
          - gh
          - git-delta
          - html-xml-utils
          - lazygit
          - neovim
          - ripgrep
          - starship
          - stylua
          - uv
        update_homebrew: true
        upgrade_all: true

    - name: install flatpaks
      community.general.flatpak:
        name:
          - ca.desrt.dconf-editor
          - com.brave.Browser
          - com.discordapp.Discord
          - com.rtosta.zapzap
          - com.slack.Slack
          - org.chromium.Chromium
          - org.gnome.Geary
          - org.signal.Signal
        state: present

    - name: remove default flatpaks
      community.general.flatpak:
        name:
          - io.github.dvlv.boxbuddyrs
          - io.podman_desktop.PodmanDesktop
          - org.mozilla.firefox
          - org.mozilla.Thunderbird
          - sh.loft.devpod
        state: absent

    - name: kitty
      block:
        - name: kitty install
          shell: "curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin"
          when: kitty_dir is not directory

        - name: kitty dirs
          ansible.builtin.file:
            path: "{{ home }}/.local/{{ item }}"
            state: directory
          loop:
            - share/applications
            - share/icons/hicolor/256x256/apps
            - bin

        - name: kitty icon
          ansible.builtin.file:
            src: "{{ kitty_dir }}/share/icons/hicolor/256x256/apps/kitty.png"
            dest: "{{ home }}/.local/share/icons/hicolor/256x256/apps/kitty.png"
            state: link

        - name: kitty bin
          ansible.builtin.file:
            src: "{{ kitty_dir }}/bin/{{ item }}"
            dest: "{{ home }}/.local/bin/{{ item }}"
            state: link
          loop:
            - kitty
            - kitten

        - name: kitty desktop
          ansible.builtin.copy:
            src: "{{ kitty_dir }}/share/applications/kitty.desktop"
            dest: "{{ home }}/.local/share/applications/kitty.desktop"

        - name: kitty desktop exec path
          ansible.builtin.replace:
            path: "{{ home }}/.local/share/applications/kitty.desktop"
            regexp: "Exec=.*"
            replace: "Exec={{ home }}/.local/bin/kitty"

        - name: kitty desktop icon path
          ansible.builtin.replace:
            path: "{{ home }}/.local/share/applications/kitty.desktop"
            regexp: "Icon=.*"
            replace: "Icon={{ home }}/.local/share/icons/hicolor/256x256/apps/kitty.png"

    - name: blesh
      block:
        - name: blesh download
          get_url:
            url: https://github.com/akinomyoga/ble.sh/releases/download/nightly/ble-nightly.tar.xz
            dest: /tmp/ble-nightly.tar.xz

        - name: blesh extract
          unarchive:
            src: /tmp/ble-nightly.tar.xz
            dest: /tmp

        - name: blesh install
          shell: "bash /tmp/ble-nightly/ble.sh --install ~/.local/share"
      when: blesh_dir is not directory

# vim:ft=yaml.ansible
