- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: "add chaotic-aur key"
      community.general.pacman_key:
        id: EF925EA60F33D0CB85C44AD13056513887B78AEB
        keyserver: keyserver.ubuntu.com
        state: present

    - name: "add chaotic-aur base packages"
      community.general.pacman:
        name:
          - https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst
          - https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst
        state: present

    - name: "add chaotic-aur to pacman.conf"
      ansible.builtin.blockinfile:
        path: /etc/pacman.conf
        prepend_newline: true
        block: |
          [chaotic-aur]
          Include = /etc/pacman.d/chaotic-mirrorlist

    - name: "install packages"
      community.general.pacman:
        name:
          - base-devel
          - bat
          - blesh-git
          - brave-browser
          - eza
          - fd
          - fzf
          - git
          - git-delta
          - github-cli
          - jq
          - kde-cli-tools
          - kitty
          - lazygit
          - mise
          - neovim
          - ripgrep
          - starship
          - stylua
          - tailwindcss-language-server
          - traefik
          - ttf-jetbrains-mono
          - ttf-nerd-fonts-symbols-mono
          - usage
          - vscode-css-languageserver
          - vscode-html-languageserver
          - vscode-json-languageserver
          - wl-clipboard
          - yay
          - yazi
        update_cache: true

    - name: "install box specific packages"
      become: true
      community.general.pacman:
        name: "{{ extra_packages[box_name] }}"
        update_cache: true
      when: "extra_packages[box_name] is defined"

    - name: "let traefik bind to privileged ports"
      community.general.capabilities:
        path: /usr/bin/traefik
        capability: cap_net_bind_service+ep
        state: present

    - name: "prepare locale.conf"
      ansible.builtin.copy:
        dest: /etc/locale.conf
        content: |
          LANG=en_US.UTF-8
          LANGUAGE=en_US:en

    - name: "prepare locale.gen"
      ansible.builtin.copy:
        dest: /etc/locale.gen
        content: |
          en_US.UTF-8 UTF-8
          pt_PT.UTF-8 UTF-8

    - name: "generate locales"
      ansible.builtin.command: locale-gen
