- hosts: localhost

  vars:
    home: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: worktree list
      ansible.builtin.find:
        paths: "{{ home }}/Worktrees"
        file_type: directory
        recurse: false
      register: worktrees

    - name: launcher template
      ansible.builtin.template:
        src: templates/worktree.desktop.j2
        dest: "{{ home }}/.local/share/applications/{{ item.path | basename }}.desktop"
        mode: "0644"
      loop: "{{ worktrees.files }}"

# vim: ft=yaml.ansible
