- name: install flatpaks
  community.general.flatpak:
    name:
      - ca.desrt.dconf-editor
      - com.bitwarden.desktop
      - com.brave.Browser
      - com.discordapp.Discord
      - com.rtosta.zapzap
      - com.slack.Slack
      - org.chromium.Chromium
      - org.gnome.Geary
      - org.signal.Signal
    state: present

- name: remove default flatpaks
  community.general.flatpak:
    name:
      - io.github.dvlv.boxbuddyrs
      - io.podman_desktop.PodmanDesktop
      - org.mozilla.firefox
      - org.mozilla.Thunderbird
      - sh.loft.devpod
    state: absent

- name: enable bluefin gnome extensions
  shell: "gnome-extensions enable {{ item }}"
  loop:
    - caffeine@patapon.info

- name: disable bluefin gnome extensions
  shell: "gnome-extensions disable {{ item }}"
  loop:
    - apps-menu@gnome-shell-extensions.gcampax.github.com
    - dash-to-dock@micxgx.gmail.com
    - logomenu@aryan_k
    - search-light@icedman.github.com
    - tailscale@joaophi.github.com

- name: download gnome extensions
  get_url:
    url: "https://extensions.gnome.org/extension-data/{{ item.file }}"
    dest: "/tmp/{{ item.file }}"
  loop: "{{ extensions }}"

- name: install gnome extensions
  command: "gnome-extensions install /tmp/{{ item.file }}"
  loop: "{{ extensions }}"
  ignore_errors: true

- name: enable gnome extensions
  command: "gnome-extensions enable {{ item.name }}"
  loop: "{{ extensions }}"
  ignore_errors: true

- name: tweak gnome settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: "/desktop/ibus/general/hotkey/triggers"
      value: "['']"
    - key: "/desktop/ibus/panel/emoji/hotkey"
      value: "['']"
    - key: "/desktop/ibus/panel/emoji/unicode-hotkey"
      value: "['']"

    - key: "/system/locale/region"
      value: "'pt_PT.UTF-8'"

    - key: "/org/gnome/desktop/input-sources/mru-sources"
      value: "[('xkb', 'us')]"
    - key: "/org/gnome/desktop/input-sources/per-window"
      value: "true"
    - key: "/org/gnome/desktop/input-sources/sources"
      value: "[('xkb', 'us'), ('xkb', 'us+intl')]"
    - key: "/org/gnome/desktop/wm/keybindings/show-desktop"
      value: "['']"
    - key: "/org/gnome/desktop/wm/keybindings/switch-group"
      value: "['']"
    - key: "/org/gnome/desktop/wm/keybindings/switch-group-backward"
      value: "['']"
    - key: "/org/gnome/desktop/wm/keybindings/switch-input-source"
      value: "['<Shift><Control><Alt>apostrophe']"

    - key: "/org/gnome/desktop/interface/accent-color"
      value: "'yellow'"
    - key: "/org/gnome/desktop/interface/clock-format"
      value: "'24h'"
    - key: "/org/gnome/desktop/interface/color-scheme"
      value: "'prefer-dark'"
    - key: "/org/gnome/desktop/interface/document-font-name"
      value: "'Inter 11'"
    - key: "/org/gnome/desktop/interface/font-antialiasing"
      value: "'grayscale'"
    - key: "/org/gnome/desktop/interface/font-name"
      value: "'Inter 11'"
    - key: "/org/gnome/desktop/interface/gtk-key-theme"
      value: "'Emacs'"
    - key: "/org/gnome/desktop/interface/monospace-font-name"
      value: "'JetBrains Mono 11'"

    - key: "/org/gnome/desktop/wm/keybindings/close"
      value: "['<Shift><Control><Alt>q']"
    - key: "/org/gnome/desktop/wm/keybindings/minimize"
      value: "['']"

    - key: "/org/gnome/desktop/wm/preferences/workspace-names"
      value: "['I', 'II', 'III']"

    - key: "/org/gnome/mutter/keybindings/restore-shortcuts"
      value: "''"
    - key: "/org/gnome/mutter/overlay-key"
      value: "''"

    - key: "/org/gnome/settings-daemon/plugins/media-keys/screensaver"
      value: "['']"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/home"
      value: "['']"

    - key: "/org/gnome/shell/extensions/arcmenu/arcmenu-hotkey"
      value: "['<Shift><Control><Alt>a']"
    - key: "/org/gnome/shell/extensions/arcmenu/force-menu-location"
      value: "MonitorCentered"
    - key: "/org/gnome/shell/extensions/arcmenu/menu-background-color"
      value: "rgba(40,40,40,0.933333)"
    - key: "/org/gnome/shell/extensions/arcmenu/menu-button-appearance"
      value: "None"
    - key: "/org/gnome/shell/extensions/arcmenu/menu-button-bg-color"
      value: "(false, 'rgba(242,242,242,0.2)')"
    - key: "/org/gnome/shell/extensions/arcmenu/menu-item-active-bg-color"
      value: "rgb(229,165,10)"
    - key: "/org/gnome/shell/extensions/arcmenu/menu-layout"
      value: "Runner"
    - key: "/org/gnome/shell/extensions/arcmenu/menu-position-alignment"
      value: "0"
    - key: "/org/gnome/shell/extensions/arcmenu/override-menu-theme"
      value: "true"
    - key: "/org/gnome/shell/extensions/arcmenu/runner-hotkey"
      value: "['']"
    - key: "/org/gnome/shell/extensions/arcmenu/runner-position"
      value: "Centered"
    - key: "/org/gnome/shell/extensions/arcmenu/search-entry-border-radius"
      value: "(true, 25)"

    - key: "/org/gnome/shell/extensions/azwallpaper/slideshow-slide-duration"
      value: "(0, 5, 0)"
    - key: "/org/gnome/shell/extensions/azwallpaper/slideshow-directory"
      value: "'/var/home/david/.local/share/backgrounds'"

    - key: "/org/gnome/shell/extensions/blur-my-shell/applications/blur"
      value: "true"
    - key: "/org/gnome/shell/extensions/blur-my-shell/applications/dynamic-opacity"
      value: false
    - key: "/org/gnome/shell/extensions/blur-my-shell/applications/opacity"
      value: "245"
    - key: "/org/gnome/shell/extensions/blur-my-shell/applications/whitelist"
      value: "['kitty']"

    - key: "/org/gnome/shell/extensions/dash-to-panel/stockgs-keep-dash"
      value: "true"
    - key: "/org/gnome/shell/extensions/dash-to-panel/trans-use-custom-opacity"
      value: "true"

    - key: "/org/gnome/shell/extensions/search-light/scale-height"
      value: "0.0"
    - key: "/org/gnome/shell/extensions/search-light/scale-width"
      value: "0.0"
    - key: "/org/gnome/shell/extensions/search-light/shortcut-search"
      value: "['<Shift><Control><Alt>a']"

    - key: "/org/gnome/shell/extensions/paperwm/cycle-width-steps"
      value: "[0.55, 0.77, 1.0]"
    - key: "/org/gnome/shell/extensions/paperwm/default-focus-mode"
      value: "1"
    - key: "/org/gnome/shell/extensions/paperwm/horizontal-margin"
      value: "6"
    - key: "/org/gnome/shell/extensions/paperwm/selection-border-radius-top"
      value: "0"
    - key: "/org/gnome/shell/extensions/paperwm/selection-border-size"
      value: "0"
    - key: "/org/gnome/shell/extensions/paperwm/show-window-position-bar"
      value: "false"
    - key: "/org/gnome/shell/extensions/paperwm/vertical-margin"
      value: "6"
    - key: "/org/gnome/shell/extensions/paperwm/vertical-margin-bottom"
      value: "6"
    - key: "/org/gnome/shell/extensions/paperwm/window-gap"
      value: "6"
    - key: "/org/gnome/shell/extensions/paperwm/winprops"
      value: |
        [
          '{"wm_class":"","title":"git","preferredWidth":"100%"}',
          '{"wm_class":"kitty","preferredWidth":"55%"}'
        ]
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/barf-out"
      value: "['']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/barf-out-active"
      value: "['']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/center-horizontally"
      value: "['']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/center-vertically"
      value: "['']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/cycle-height"
      value: "['']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/cycle-width"
      value: "['<Shift><Control><Alt>u']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/cycle-width-backwards"
      value: "['<Shift><Control><Alt>i']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/move-down-workspace"
      value: "['<Shift><Control><Alt><Super>j']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/move-left"
      value: "['<Shift><Control><Alt><Super>h']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/move-right"
      value: "['<Shift><Control><Alt><Super>l']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/move-up-workspace"
      value: "['<Shift><Control><Alt><Super>k']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/new-window"
      value: "['']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/previous-workspace"
      value: "['']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/previous-workspace-backward"
      value: "['']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/paper-toggle-fullscreen"
      value: "['']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/slurp-in"
      value: "['']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/switch-down-workspace"
      value: "['<Shift><Control><Alt>j']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/switch-focus-mode"
      value: "['']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/switch-left"
      value: "['<Shift><Control><Alt>h']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/switch-next"
      value: "['']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/switch-open-window-position"
      value: "['']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/switch-previous"
      value: "['']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/switch-right"
      value: "['<Shift><Control><Alt>l']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/switch-up-workspace"
      value: "['<Shift><Control><Alt>k']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/take-window"
      value: "['']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/toggle-scratch-window"
      value: "['']"
    - key: "/org/gnome/shell/extensions/paperwm/keybindings/toggle-maximize-width"
      value: "['']"

      # Favorite app shortcuts
    - key: "/org/gnome/shell/favorite-apps"
      value: |
        [
          'com.discordapp.Discord.desktop',
          'com.rtosta.zapzap.desktop',
          'com.brave.Browser.desktop'
        ]
    - key: "/org/gnome/shell/keybindings/switch-to-application-1"
      value: "['<Shift><Control><Alt>d']"
    - key: "/org/gnome/shell/keybindings/switch-to-application-2"
      value: "['<Shift><Control><Alt>z']"
    - key: "/org/gnome/shell/keybindings/switch-to-application-3"
      value: "['<Shift><Control><Alt>b']"

    - key: "/org/gnome/shell/keybindings/toggle-application-view"
      value: "['']"
    - key: "/org/gnome/shell/keybindings/toggle-message-tray"
      value: "['']"
    - key: "/org/gnome/shell/keybindings/toggle-overview"
      value: "['<Shift><Control><Alt>o']"
    - key: "/org/gnome/shell/keybindings/toggle-quick-settings"
      value: "['']"

    - key: "/org/gtk/settings/file-chooser/clock-format"
      value: "'24'"
