git:
  paging:
    colorArg: always
    pager: delta --paging=never
gui:
  border: hidden
  enlargedSideViewLocation: top
  nerdFontsVersion: 3
  screenMode: half
  sidePanelWidth: 0.15
  showCommandLog: false
  showListFooter: false
  showNumstatInFilesView: true
  showRandomTip: false
keybindings:
  commits:
    copyCommitAttributeToClipboard: "<c-o>"
  files:
    copyFileInfoToClipboard: "<c-o>"
  universal:
    copyToClipboard: "y"
os:
  editPreset: nvim
promptToReturnFromSubprocess: false
update:
  method: never
