source ~/.profile

export CDPATH=".:~/Worktrees"

[[ $- == *i* ]] || return

set -o vi

[[ -f ~/.local/share/blesh/ble.sh ]] &&
  source ~/.local/share/blesh/ble.sh

[[ -f /usr/share/blesh/ble.sh ]] &&
  source /usr/share/blesh/ble.sh

alias ls=eza
alias ap=ansible-playbook

eval "$(fzf --bash)"
eval "$(mise activate bash --shims)"
eval "$(starship init bash)"

[[ ! ${BLE_VERSION-} ]] || ble-attach

# vim: ft=bash

