- name: create
  ansible.builtin.command:
    argv:
      - distrobox
      - create
      - --name
      - "{{ item }}"
      - --image
      - "ghcr.io/ublue-os/ubuntu-toolbox:latest"
      - --yes
      - --additional-packages
      - "{{ additional_packages }}"
      - --no-entry
      - --init
  loop: "{{ groups['boxes'] }}"
  tags: boxes

- name: warm up
  ansible.builtin.command: "distrobox enter {{ item }} -- true"
  loop: "{{ groups['boxes'] }}"
  tags: boxes

# vim: ft=yaml.ansible
