- name: create
  ansible.builtin.command:
    argv:
      - distrobox
      - create
      - --name
      - "{{ item }}"
      - --image
      - "{{ box_defaults.image }}"
      - --yes
      - --home
      - "{{ box_defaults.prefix }}/{{ item }}"
      - --additional-packages
      - "{{ additional_packages }}"
      - --no-entry
      - --volume
      - "{{ home }}/.local/share/nvim/site:{{ home }}/Boxes/{{ item }}/.local/share/nvim/site"
      - --volume
      - "{{ home }}/.supermaven:{{ home }}/Boxes/{{ item }}/.supermaven"
  loop: "{{ groups['boxes'] }}"
  tags: boxes

- name: warm up
  ansible.builtin.command: "distrobox enter {{ item }} -- true"
  loop: "{{ groups['boxes'] }}"
  tags: boxes

# vim: ft=yaml.ansible
