umask 077

[[ -f /var/home/linuxbrew/.linuxbrew/bin/brew ]] &&
  eval "$(/var/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

export CDPATH=".:$HOME/Boxes"

# history

if [[ -v CONTAINER_ID ]] ; then
  export HISTFILE=~/.${CONTAINER_ID}.bash_history
fi

# editor
export EDITOR=nvim
export VISUAL=nvim

# fzf
export FZF_DEFAULT_OPTS="--reverse --preview-window=bottom,66%"

# mise
if command -v mise > /dev/null ; then
  eval "$(mise activate bash --shims)"

  export PATH="$HOME/.local/share/mise/shims:$PATH"
fi

# elixir
export ERL_AFLAGS="-kernel shell_history enabled"

# secrets
source ~/.config/bash/secrets.bash

# container
CONTAINERRC=~/.config/bash/${CONTAINER_ID}.bash
CONTAINER_SECRETS=~/.config/bash/${CONTAINER_ID}.secrets.bash

if [[ -f $CONTAINERRC ]] ; then
  source $CONTAINERRC
fi

if [[ -f $CONTAINER_SECRETS ]] ; then
  source $CONTAINER_SECRETS
fi

# path
export PATH="$HOME/.local/bin:$PATH"

[[ $- == *i* ]] || return

set -o vi

[[ -f $HOME/.local/share/blesh/ble.sh ]] &&
  source $HOME/.local/share/blesh/ble.sh --noattach

alias ls=eza

eval "$(fzf --bash)"
eval "$(direnv hook bash)"
eval "$(starship init bash)"

[[ ! ${BLE_VERSION-} ]] || ble-attach

# vim:ft=bash
