- hosts: localhost

  vars:
    home: "{{ ansible_user_dir }}"

    plugins_base_dir: "{{ home }}/.local/share/nvim/site/pack/plugins/start"
    plugins:
      - repo: Olical/conjure
      - repo: Olical/nfnl
      - repo: akinsho/toggleterm.nvim
      - repo: echasnovski/mini.nvim
      - repo: ellisonleao/gruvbox.nvim
      - repo: folke/snacks.nvim
      - repo: folke/which-key.nvim
      - repo: ggandor/leap.nvim
      - repo: mfussenegger/nvim-lint
      - repo: nvim-lualine/lualine.nvim
      - repo: nvim-treesitter/nvim-treesitter
        branch: main
      - repo: stevearc/conform.nvim
      - repo: tpope/vim-repeat
      - repo: HiPhish/rainbow-delimiters.nvim
        provider: gitlab

    treesitter_parsers:
      - fennel
      - javascript
      - json
      - regex
      - yaml

  tasks:
    - name: plugin base directory
      ansible.builtin.file:
        path: "{{ plugins_base_dir }}"
        state: directory
        mode: "0755"
      tags:
        - plugins

    - name: clone or update plugins
      ansible.builtin.git:
        repo: "https://{{ provider | default('github') }}.com/{{ item.repo }}.git"
        dest: "{{ plugins_base_dir }}/{{ item.repo | split('/') | last }}"
        version: "{{ item.branch | default('HEAD') }}"
        update: yes
        force: yes
      loop: "{{ plugins }}"
      tags:
        - plugins

    - name: helptags
      ansible.builtin.command:
        argv: 
          - nvim 
          - --headless 
          - "+helptags ++t ALL"
          - "+qa"
      tags:
        - plugins

    - name: config directory
      ansible.builtin.file:
        path: "{{ home }}/.config/nvim"
        state: directory
        mode: "0755"
      tags:
        - files

    - name: config subdirectories
      ansible.builtin.file:
        path: "{{ home }}/.config/nvim/{{ item.path }}"
        state: directory
        mode: "0755"
      with_community.general.filetree: "files/"
      when: item.state == 'directory'
      tags:
        - files

    - name: config files
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ home }}/.config/nvim/{{ item.path }}"
        state: link
        force: yes
      with_community.general.filetree: "files/"
      when: item.state == 'file'
      tags:
        - files

    - name: treesitter parsers
      ansible.builtin.command:
        argv: 
          - nvim 
          - --headless 
          - "+lua require('nvim-treesitter').install({ '{{item}}' }):wait(300000)"
          - "+qa"
      loop: "{{ treesitter_parsers }}"
      tags:
        - ts

# vim: ft=yaml.ansible
