extensions:
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
GOOSE_MODEL: gemini-2.5-flash-preview-05-20
GOOSE_PLANNER_MODEL: gemini-2.5-pro-preview-05-06
GOOSE_CLI_THEME: ansi
GOOSE_PLANNER_PROVIDER: google
GOOSE_PROVIDER: google
