- name: "create config subdirs"
  ansible.builtin.file:
    path: "{{ config_home }}/{{ item.path }}"
    state: directory
    mode: "0700"
  with_community.general.filetree: "{{ config_src }}"
  when: item.state == 'directory'

- name: "link config files"
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ config_home }}/{{ item.path }}"
    state: link
  with_community.general.filetree: "{{ config_src }}"
  when: item.state == 'file'

- name: "remove default bash files"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ home }}/.bashrc"
    - "{{ home }}/.bash_profile"
  when: item is not link

- name: "link home root files"
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ home }}/.{{ item.path }}"
    state: link
  with_community.general.filetree: "{{ home_src }}"
  when: item.path is not link

# vim:ft=yaml.ansible
