#!/bin/sh

box="$1"

HOST_HOME=/var/home/david
BOX_HOME_PREFIX="${HOST_HOME}/Homes"
DOT_HOME="${BOX_HOME_PREFIX}/dot/dot"

echo "BOX_HOME_PREFIX=${BOX_HOME_PREFIX}"
echo "BOX_IMAGE=ghcr.io/david/devbox:latest"
echo "BOX_GID=$(id --group)"
echo "BOX_UID=$(id --user)"
echo "BOX_USER=$(id --user --name)"
echo "DOT_HOME=${DOT_HOME}"
echo "HOST_HOME=${HOST_HOME}"

if [[ -n "$box" ]] ; then
  echo "BOX_HOME=${BOX_HOME_PREFIX}/${box}"
fi
