#!/bin/bash

eval "$(scripts/boxcfg)"

podman build \
  --build-arg "GID=${BOX_GID}" \
  --build-arg "UID=${BOX_UID}" \
  --build-arg "USER=${BOX_USER}" \
  --file box/Dockerfile \
  --tag $BOX_IMAGE \
  .
