#!/bin/bash

set -e

box="$1"

eval "$(scripts/boxcfg $box)"

distrobox create \
  --home $BOX_HOME \
  --image $BOX_IMAGE \
  --init-hooks " \
    cd $DOT_HOME && \
    chown ${BOX_USER}:${BOX_USER} ${BOX_HOME}/{.local,.local/share,.local/share/nvim} && \
    mkdir -p ${BOX_HOME}/.config && \
    chown ${BOX_USER}:${BOX_USER} ${BOX_HOME}/.config \
  " \
  --name $1 \
  --no-entry \
  --volume ${HOME}/.local/share/nvim:${BOX_HOME}/.local/share/nvim \
  --yes

distrobox enter $box -- scripts/mkcfg
distrobox enter $box -- distrobox-export \
  --app neovide \
  --export-label "[$box]" \
  --enter-flags "--no-workdir"
