#!/bin/bash

echo "Starting '"$@"' in $(pwd)"

direnv exec . "$@"
. $HOME/.bashrc

echo
echo "ENTER to relaunch, CTRL-C to exit"
echo -n "[$@]: "
read -e COMMAND || exit 1

if [[ -n "$COMMAND" ]] ; then
  exec $0 $COMMAND
else
  exec $0 "$@"
fi
