#!/bin/bash

SYS_DIR=$HOME/Boxes/sys/trunk

if [[ "$1" == "host" ]]; then
  case "$2" in
    apps)
      distrobox-host-exec ansible-playbook --tags apps $SYS_DIR/files.yaml
      ;;
  esac
elif [[ -v CONTAINER_ID ]]; then
  ansible-playbook $SYS_DIR/${CONTAINER_ID}.yaml
fi
