#!/usr/bin/env bash

set -euo pipefail

script_path=$(realpath ${BASH_SOURCE[0]})
script_dir="$(dirname $script_path)"

module="${1:-}"

if [[ -z "$module" ]] ; then
  >&2 echo "missing module argument"

  exit 1
fi

if [[ "$module" == "setup" ]] ; then
  echo "Making 'sys' binary available in \$PATH"

  mkdir -p $HOME/.local/bin

  ln -sf $script_path $HOME/.local/bin/sys

  exit 0
fi

shift

module_script="$script_dir/sys.$module"

if [[ ! -x $module_script ]] ; then
  >&2 echo "module $(basename $module_script) not found"
  exit 1
fi

exec bash $module_script "$@"
