- name: "create config subdirs"
  become: true
  become_user: david
  ansible.builtin.file:
    path: "{{ home }}/.config/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "home-config/"
  when: item.state == 'directory'
  tags: files

- name: "link config files"
  become: true
  become_user: david
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ home }}/.config/{{ item.path }}"
    state: link
  with_community.general.filetree: "home-config/"
  when: item.state == 'file'
  tags: files

- name: "remove default files"
  become: true
  become_user: david
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ home }}/.bashrc"
    - "{{ home }}/.bash_profile"
    - "{{ home }}/.profile"
  when: item is not link
  tags: files

- name: "link home root files"
  become: true
  become_user: david
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ home }}/.{{ item.path }}"
    state: link
  with_community.general.filetree: "home/"
  when: item.path is not link
  tags: files

# vim:ft=yaml.ansible

