- name: .config
  ansible.builtin.file:
    path: "{{ home }}/.config"
    mode: "0755"
    owner: david
    group: david
    state: directory
  tags:
    - files
    - config

- name: .local
  ansible.builtin.file:
    path: "{{ home }}/.local"
    mode: "0755"
    owner: david
    group: david
    state: directory
  tags:
    - files

- name: .local
  ansible.builtin.file:
    path: "{{ home }}/.local/share"
    mode: "0755"
    owner: david
    group: david
    state: directory
  tags:
    - files

- name: "create config subdirs"
  become: true
  become_user: david
  ansible.builtin.file:
    path: "{{ home }}/.config/{{ item.path }}"
    mode: "0755"
    owner: "david"
    group: "david"
    state: directory
  with_community.general.filetree:
    - home-config/
    - secrets-config/
  when: item.state == 'directory'
  tags:
    - files
    - config

- name: "link config files"
  become: true
  become_user: david
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ home }}/.config/{{ item.path }}"
    mode: "0644"
    owner: "david"
    group: "david"
    state: link
  with_community.general.filetree:
    - home-config/
    - secrets-config/
  when: item.state == 'file'
  tags:
    - files
    - config

- name: "remove default files"
  become: true
  become_user: david
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ home }}/.bashrc"
    - "{{ home }}/.bash_profile"
    - "{{ home }}/.profile"
  when: item is not link
  tags:
    - files
    - config

- name: "link home root files"
  become: true
  become_user: david
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ home }}/.{{ item.path }}"
    mode: "0644"
    owner: "david"
    group: "david"
    state: link
  with_community.general.filetree: "home/"
  when: item.path is not link
  tags:
    - files
    - config

# vim:ft=yaml.ansible
