- name: mcp-proxy
  ansible.builtin.unarchive:
    src: https://github.com/tidewave-ai/mcp_proxy_rust/releases/download/v0.2.0/mcp-proxy-x86_64-unknown-linux-gnu.tar.gz
    dest: /usr/local/bin
    remote_src: true
  tags: ai

# vim: ft=yaml.ansible
