- name: chaotic-aur pacman key
  become: true
  community.general.pacman_key:
    id: ef925ea60f33d0cb85c44ad13056513887b78aeb
    keyserver: keyserver.ubuntu.com
    state: present

- name: chaotic-aur repo packages
  become: true
  community.general.pacman:
    name:
      - https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst
      - https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst

- name: chaotic-aur pacman config
  become: true
  community.general.ini_file:
    path: /etc/pacman.conf
    mode: "0644"
    section: chaotic-aur
    option: Include
    value: /etc/pacman.d/chaotic-mirrorlist
    state: present

- name: packages
  become: true
  community.general.pacman:
    name:
      - bat
      - direnv
      - eza
      - fd
      - fzf
      - github-cli
      - gnome-keyring
      - jq
      - kitty
      - lazygit
      - neovim
      - nodejs
      - npm
      - org.freedesktop.secrets
      - ripgrep
      - ruby
      - starship
      - tailwindcss-language-server
      - wl-clipboard
      - yay
    update_cache: true
  tags: packages

# vim: ft=yaml.ansible
