- name: packages
  community.general.pacman:
    name:
      - ansible-language-server
      - ansible-lint
      - lua-language-server
      - stylua
      - yaml-language-server
    state: present
  tags: packages

