- name: blesh clean
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/local/blesh
    - /tmp/ble-nightly.tar.xz
    - /tmp/ble-nightly
  tags: packages

- name: blesh prepare
  ansible.builtin.unarchive:
    src: https://github.com/akinomyoga/ble.sh/releases/download/nightly/ble-nightly.tar.xz
    dest: /tmp
    remote_src: true
  tags: packages

- name: blesh install
  become: true
  ansible.builtin.command:
    cmd: bash /tmp/ble-nightly/ble.sh --install /usr/local
    creates: /usr/local/blesh
  tags: packages

# vim: ft=yaml.ansible

