- name: apt install
  ansible.builtin.apt:
    name:
      - fonts-jetbrains-mono
    state: latest
  tags:
    - fonts

- name: nerd fonts dir
  ansible.builtin.file:
    path: /usr/share/fonts/truetype/nerd-fonts
    state: directory
    mode: "0755"
  tags:
    - fonts

- name: install nerd fonts
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/NerdFontsSymbolsOnly.zip
    dest: /usr/share/fonts/truetype/nerd-fonts
    remote_src: true
    creates: /usr/share/fonts/truetype/nerd-fonts/SymbolsNerdFontMono-Regular.ttf
  tags:
    - fonts

# vim: ft=yaml.ansible
