- name: .config
  ansible.builtin.file:
    path: "{{ home }}/.config"
    mode: "0755"
    state: directory
  tags: home

- name: .local
  ansible.builtin.file:
    path: "{{ home }}/.local"
    mode: "0755"
    owner: david
    group: david
    state: directory
  tags: home

- name: .local
  ansible.builtin.file:
    path: "{{ home }}/.local/share"
    mode: "0755"
    owner: david
    group: david
    state: directory
  tags: home

- name: "common files"
  include_tasks: ../../common/tasks/files.yaml

# vim:ft=yaml.ansible
