- name: .config
  ansible.builtin.file:
    path: "{{ config_home }}"
    mode: "0755"
    state: directory
  tags: home

- name: .local
  ansible.builtin.file:
    path: "{{ home }}/.local"
    mode: "0755"
    owner: david
    group: david
    state: directory
  tags: home

- name: .local
  ansible.builtin.file:
    path: "{{ home }}/.local/share"
    mode: "0755"
    owner: david
    group: david
    state: directory
  tags: home

- name: "create config subdirs"
  become: true
  become_user: david
  ansible.builtin.file:
    path: "{{ config_home }}/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "{{ config_src }}"
  when: item.state == 'directory'
  tags: home

- name: "link config files"
  become: true
  become_user: david
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ config_home }}/{{ item.path }}"
    state: link
  with_community.general.filetree: "{{ config_src }}"
  when: item.state == 'file'
  tags: home

- name: "remove default bash files"
  become: true
  become_user: david
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ home }}/.bashrc"
    - "{{ home }}/.bash_profile"
  when: item is not link
  tags: home

- name: "link home root files"
  become: true
  become_user: david
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ home }}/.{{ item.path }}"
    state: link
  with_community.general.filetree: "{{ home_src }}"
  when: item.path is not link
  tags: home

# vim:ft=yaml.ansible
