- name: apt update
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist

- name: apt install
  ansible.builtin.apt:
    name:
      - fonts-jetbrains-mono
      - wl-clipboard
    state: latest

- name: homebrew install script
  become: true
  become_user: david
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    mode: "0755"
    dest: /tmp/brew-install.sh
  tags:
    - packages

- name: homebrew install
  become: true
  become_user: david
  ansible.builtin.command:
    argv:
      - /bin/bash
      - /tmp/brew-install.sh
    creates: /home/linuxbrew
  environment:
    NONINTERACTIVE: 1
  tags:
    - packages

- name: dev tools
  become: true
  become_user: david
  community.general.homebrew:
    name:
      - bat
      - eza
      - fd
      - fzf
      - gh
      - jq
      - lazygit
      - neovim
      - ripgrep
      - starship
    state: latest
  tags:
    - packages

- name: dot
  become: true
  become_user: david
  community.general.homebrew:
    name:
      - ansible-language-server
      - ansible-lint
      - lua-language-server
      - stylua
  when: ansible_env.CONTAINER_ID == "dot"
  tags:
    - packages

# vim: ft=yaml.ansible
