- name: whisper
  ansible.builtin.pacman:
    name:
      - alsa-utils
      - libggml-git
      - libnotify
      - sox
      - whisper-cpp-git
      - ydotool
      # For wsi:
      - zsh
    update_cache: true
  tags: voice

- name: whisper model
  ansible.builtin.command:
    argv:
      - yay
      - -S
      - --noconfirm
      - --needed
      - whisper.cpp-model-large-v3-turbo-q5_0
  tags: voice

- name: clone
  ansible.builtin.git:
    repo: https://github.com/QuantiusBenignus/blahst.git
    dest: /usr/local/blahst
    update: true
    force: true
  tags: voice

- name: configure
  ansible.builtin.lineinfile:
    path: /usr/local/blahst/wsi
    regexp: '^WMODEL='
    line: 'WMODEL=/usr/share/whisper.cpp-model-large-v3-turbo-q5_0/ggml-large-v3-turbo-q5_0.bin'
  tags: voice

- name: configure
  ansible.builtin.lineinfile:
    path: /usr/local/blahst/wsi
    regexp: '^#---CHECK DEPENDENCIES'
    line: '# BEGIN CHECK DEPENDENCIES'
  tags: voice

- name: configure
  ansible.builtin.lineinfile:
    path: /usr/local/blahst/wsi
    regexp: '^#---END CHECK DEPENDENCIES'
    line: '# END CHECK DEPENDENCIES'
  tags: voice

- name: configure
  ansible.builtin.blockinfile:
    path: /usr/local/blahst/wsi
    marker: "# {mark} CHECK DEPENDENCIES"
    marker_begin: "BEGIN"
    marker_end: "END"
    block: ""
  tags: voice

- name: patch
  ansible.builtin.lineinfile:
    path: /usr/local/blahst/wsi
    insertafter: "#---USER CONFIGURATION BLOCK"
    regexp: '^DBUS_SESSION_BUS_ADDRESS='
    line: "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/host/run/user/1000/bus"
  tags: voice

- name: make executable
  ansible.builtin.file:
    path: "/usr/local/blahst/{{ item }}"
    mode: "0755"
  loop:
    - wsi
    - wsiAI
    - wsiml
    - blooper
    - blahstbot
  tags: voice

- name: link
  ansible.builtin.file:
    src: "/usr/local/blahst/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - wsi
    - wsiAI
    - wsiml
    - blooper
    - blahstbot
  tags: voice

- name: link whisper
  ansible.builtin.file:
    src: /usr/sbin/whisper-cli
    dest: /usr/local/bin/transcribe
    state: link
  tags: voice

# vim: ft=yaml.ansible
