- name: packages
  community.general.pacman:
    name:
      - postgresql
      - python-psycopg
    state: present

- name: postgres init db
  become: true
  become_user: postgres
  ansible.builtin.command:
    argv:
      - initdb
      - --pgdata
      - /var/lib/postgres/data
    creates: /var/lib/postgres/data/postgresql.conf
  tags: postgres

- name: postgres start
  ansible.builtin.systemd_service:
    name: postgresql.service
    enabled: true
    state: started
  tags: postgres

- name: postgres user
  community.postgresql.postgresql_user:
    name: david
    role_attr_flags: CREATEDB,SUPERUSER
  tags: postgres
