- name: postgres key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  tags:
    - postgres

- name: postgres repo
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
  tags:
    - postgres

- name: postgres install
  ansible.builtin.apt:
    name:
      - postgresql-17
      - postgresql-client-17
      - python3-psycopg2
    state: latest
  tags:
    - postgres

- name: postgres service
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true
  tags:
    - postgres

- name: postgres user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: david
    role_attr_flags: CREATEDB,CREATEROLE,SUPERUSER
  tags:
    - postgres
