[[ -d /home/linuxbrew ]] &&
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

source ~/.profile

# history
[[ -v CONTAINER_ID ]] && HISTFILE=~/.bash_history.${CONTAINER_ID}

[[ $- == *i* ]] || return

set -o vi

[[ -f ~/.local/share/blesh/ble.sh ]] &&
  source ~/.local/share/blesh/ble.sh

alias ls=eza

eval "$(fzf --bash)"
eval "$(direnv hook bash)"
eval "$(starship init bash)"

[[ ! ${BLE_VERSION-} ]] || ble-attach

# vim: ft=bash

