GOOSE_CLI_THEME: ansi
extensions:
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  tidewave:
    args:
    - http://localhost:4000/tidewave/mcp
    bundled: null
    cmd: mcp-proxy
    description: null
    enabled: true
    env_keys: []
    envs: {}
    name: tidewave
    timeout: 300
    type: stdio
GOOSE_PLANNER_MODEL: gemini-2.5-pro-preview-06-05
GOOSE_PLANNER_PROVIDER: google
GOOSE_PROVIDER: google
GOOSE_MODEL: gemini-2.5-pro-preview-06-05
