GOOSE_MODEL: gemini-2.5-pro-preview-05-06
extensions:
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  tidewave:
    bundled: null
    description: null
    enabled: true
    env_keys: []
    envs: {}
    name: Tidewave
    timeout: 300
    type: sse
    uri: http://localhost:4000/tidewave/mcp
GOOSE_CLI_THEME: ansi
GOOSE_PLANNER_MODEL: gemini-2.5-pro-preview-05-06
GOOSE_PLANNER_PROVIDER: google
GOOSE_PROVIDER: google
